[package]
name = "olecli"
version = "0.1.2"
description = "An example crate."
authors = ["Marirs <marirs@gmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2021"


[dependencies]
ole = {path="../common", features=["blocking", "async"]}
tokio = {version="1.20.1", features=["full"]}